# URL for getting the token
tokenEndpoint=http://localhost:49000/oauth/token
# user name
userName=0oa157tvtugfFXEhU4x7
# user password
userPassword=X7eBCXqlFC7x-mjxG5H91IRv_Bqe1oq7ZwXNA8aq
# client credentials grant
grantType=grant_type=client_credentials&scope=
