# client credentials grant
grantType=client_credentials
# zip-codes
zipCodesURL=http://localhost:49000/zip-codes
# zip-codes/expand
zipCodesExpandURL=http://localhost:49000/zip-codes/expand
# users
usersURL=http://localhost:49000/users
