# OAuth 2.0 Grant Type used for server-to-server communication to obtain access tokens
grantType=client_credentials

# Base URL for zip code retrieval operations, used in API request to POST /zip-codes
zipCodesURL=http://localhost:49000/zip-codes

# URL for expanding zip codes with additional details, used in API request to POST /zip-codes/expand
zipCodesExpandURL=http://localhost:49000/zip-codes/expand

# URL for managing users, includes operations such as POST /users for new user creation
usersURL=http://localhost:49000/users
