name: Test API
on:
  push:
    branches: [ final ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TOKEN_ENDPOINT: ${{ secrets.TOKEN_ENDPOINT }}
      USERNAME2: ${{ secrets.USERNAME2 }}
      PASSWORD: ${{ secrets.PASSWORD }}
      grantType: ${{ secrets.GRANT_TYPE }}
      zipCodesURL: ${{ secrets.ZIP_CODES_URL }}
      zipCodesExpandURL: ${{ secrets.ZIP_CODES_EXPAND_URL }}
      usersURL: ${{ secrets.USERS_URL }}
      usersUploadURL: ${{ secrets.USERS_UPLOAD_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
            maven-version: 3.8.2
      - name: Deploy API Docker Image
        run: |
          docker pull coherentsolutions/rest-training:2.0
          docker run -d -p 49000:8082 coherentsolutions/rest-training:2.0
          echo "Waiting for API to be ready"
          sleep 30
      - name: Build with Maven
        run: mvn clean install
      - name: Run Tests
        run: mvn test
      - name: Upload junit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
      - name: Generate Allure test report
        if: always()
        run: mvn allure:report
      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: allure-report
            path: target/site/allure-maven-plugin